### ISSUE TITLE
Error parsing body - doesn't seem to be a chunked message

### ISSUE THREAD

**Issue by bateaurouge** [philwinkle/Philwinkle_Fixerio#32]
Hello,

I am getting this error in exception log when retrieving rates on a Magento 1.6 site. Anyone have any ideas? Thanks

exception 'Zend_Http_Exception' with message 'Error parsing body - doesn't seem to be a chunked message' in /chroot/home/web/html/lib/Zend/Http/Response.php:579
Stack trace:
#0 /chroot/home/web/html/lib/Zend/Http/Response.php(262): Zend_Http_Response::decodeChunkedBody('{"success":true...')
#1 /chroot/home/web/html/app/code/community/Philwinkle/Fixerio/Model/Import.php(86): Zend_Http_Response->getBody()
#2 /chroot/home/web/html/app/code/core/Mage/Directory/Model/Currency/Import/Abstract.php(108): Philwinkle_Fixerio_Model_Import->_convert('USD', 'AED')
#3 /chroot/home/web/html/app/code/core/Mage/Adminhtml/controllers/System/CurrencyController.php(77): Mage_Directory_Model_Currency_Import_Abstract->fetchRates()
#4 /chroot/home/web/html/app/code/core/Mage/Core/Controller/Varien/Action.php(420): Mage_Adminhtml_System_CurrencyController->fetchRatesAction()
#5 /chroot/home/web/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('fetchRates')
#6 /chroot/home/web/html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#7 /chroot/home/web/html/app/code/core/Mage/Core/Model/App.php(347): Mage_Core_Controller_Varien_Front->dispatch()
#8 /chroot/home/web/html/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#9 /chroot/home/web/html/index.php(83): Mage::run('', 'store')
#10 {main}

**Comment by bateaurouge** [comment]
I setup an overwrite for lib/Varien/Http/Adapter/Curl.php and replaced the 1.6 version with a copy from Magento 1.8.1
